extends Node2D


var CARDS_DATA = [
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a1',
	"price": 1,
	"name": 'Agumon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 5,
	"healthPoints": 3,
	"energyCount": 1,
	"evolution": '664e8b7ceb0218b7c40ce0a2',
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a2',
	"price": 4,
	"name": 'Greymon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 20,
	"healthPoints": 20,
	"evolution": '664e8b7ceb0218b7c40ce0a3',
	"energyCount": 2,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a3',
	"price": 7,
	"name": 'MetalGreymon (Vaccine)',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 34,
	"healthPoints": 32,
	"evolution": '664e8b7ceb0218b7c40ce0a4',
	"energyCount": 3,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a4',
	"price": 10,
	"name": 'WarGreymon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 60,
	"healthPoints": 55,
	"evolution": null,
	"energyCount": 4,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a5',
	"price": 1,
	"name": 'Gabumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 4,
	"healthPoints": 3,
	"evolution": '664e8b7ceb0218b7c40ce0a6',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a6',
	"price": 4,
	"name": 'Garurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 14,
	"healthPoints": 14,
	"evolution": '664e8b7ceb0218b7c40ce0a7',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a7',
	"price": 7,
	"name": 'WereGarurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 32,
	"healthPoints": 30,
	"evolution": '664e8b7ceb0218b7c40ce0a8',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a8',
	"price": 10,
	"name": 'MetalGarurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 55,
	"healthPoints": 60,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a9',
	"price": 1,
	"name": 'Veemon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 4,
	"healthPoints": 4,
	"evolution": '664e8b7ceb0218b7c40ce0aa',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0aa',
	"price": 4,
	"name": 'ExVeemon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 17,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0ab',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ab',
	"price": 7,
	"name": 'Paildramon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 35,
	"healthPoints": 30,
	"evolution": '664e8b7ceb0218b7c40ce0ac',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ac',
	"price": 10,
	"name": 'Imperialdramon Fighter Mode',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 65,
	"healthPoints": 50,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ad',
	"price": 1,
	"name": 'Patamon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 1,
	"healthPoints": 4,
	"evolution": '664e8b7ceb0218b7c40ce0ae',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ae',
	"price": 4,
	"name": 'Angemon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 14,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0af',
	"energyCount": 2,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0af',
	"price": 7,
	"name": 'MagnaAngemon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 31,
	"healthPoints": 33,
	"evolution": '664e8b7ceb0218b7c40ce0b0',
	"energyCount": 3,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b0',
	"price": 10,
	"name": 'Seraphimon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 50,
	"healthPoints": 65,
	"evolution": null,
	"energyCount": 4,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b1',
	"price": 1,
	"name": 'Salamon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 0,
	"healthPoints": 5,
	"evolution": '664e8b7ceb0218b7c40ce0b2',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b2',
	"price": 4,
	"name": 'Gatomon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 13,
	"healthPoints": 14,
	"evolution": '664e8b7ceb0218b7c40ce0b3',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b3',
	"price": 7,
	"name": 'Angewomon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 31,
	"healthPoints": 33,
	"evolution": '664e8b7ceb0218b7c40ce0b4',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b4',
	"price": 10,
	"name": 'Ophanimon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 65,
	"healthPoints": 50,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b5',
	"price": 1,
	"name": 'Biyomon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 2,
	"healthPoints": 2,
	"evolution": '664e8b7ceb0218b7c40ce0b6',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b6',
	"price": 4,
	"name": 'Birdramon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 11,
	"healthPoints": 9,
	"evolution": '664e8b7ceb0218b7c40ce0b7',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b7',
	"price": 7,
	"name": 'Garudamon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 30,
	"healthPoints": 25,
	"evolution": '664e8b7ceb0218b7c40ce0b8',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b8',
	"price": 10,
	"name": 'Phoenixmon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 45,
	"healthPoints": 43,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b9',
	"price": 1,
	"name": 'Tentomon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 2,
	"healthPoints": 3,
	"evolution": '664e8b7ceb0218b7c40ce0ba',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ba',
	"price": 4,
	"name": 'Kabuterimon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 14,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0bb',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0bb',
	"price": 7,
	"name": 'MegaKabuterimon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 33,
	"healthPoints": 36,
	"evolution": '664e8b7ceb0218b7c40ce0bc',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0bc',
	"price": 10,
	"name": 'HerculesKabuterimon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 50,
	"healthPoints": 50,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0bd',
	"price": 1,
	"name": 'Palmon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 2,
	"healthPoints": 2,
	"evolution": '664e8b7ceb0218b7c40ce0be',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0be',
	"price": 4,
	"name": 'Togemon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 12,
	"healthPoints": 12,
	"evolution": '664e8b7ceb0218b7c40ce0bf',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0bf',
	"price": 7,
	"name": 'Lillymon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 27,
	"healthPoints": 25,
	"evolution": '664e8b7ceb0218b7c40ce0c0',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c0',
	"price": 10,
	"name": 'Rosemon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 45,
	"healthPoints": 45,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c1',
	"price": 1,
	"name": 'Gomamon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 2,
	"healthPoints": 3,
	"evolution": '664e8b7ceb0218b7c40ce0c2',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c2',
	"price": 4,
	"name": 'Ikkakumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 13,
	"healthPoints": 13,
	"evolution": '664e8b7ceb0218b7c40ce0c3',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c3',
	"price": 7,
	"name": 'Zudomon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 34,
	"healthPoints": 30,
	"evolution": '664e8b7ceb0218b7c40ce0c4',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c4',
	"price": 10,
	"name": 'Vikemon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 45,
	"healthPoints": 43,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c5',
	"price": 1,
	"name": 'Elecmon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 2,
	"healthPoints": 1,
	"evolution": '664e8b7ceb0218b7c40ce0c6',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c6',
	"price": 4,
	"name": 'Leomon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 16,
	"healthPoints": 18,
	"evolution": '664e8b7ceb0218b7c40ce0c7',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c7',
	"price": 7,
	"name": 'IceLeomon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 21,
	"healthPoints": 17,
	"evolution": '664e8b7ceb0218b7c40ce0c8',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c8',
	"price": 10,
	"name": 'Saberdramon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 40,
	"healthPoints": 40,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c9',
	"price": 1,
	"name": 'Renamon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 4,
	"healthPoints": 4,
	"evolution": '664e8b7ceb0218b7c40ce0ca',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ca',
	"price": 4,
	"name": 'Kyubimon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 15,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0cb',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0cb',
	"price": 7,
	"name": 'Taomon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 32,
	"healthPoints": 30,
	"evolution": '664e8b7ceb0218b7c40ce0cc',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0cc',
	"price": 10,
	"name": 'Sakuyamon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 50,
	"healthPoints": 50,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0cd',
	"price": 1,
	"name": 'Terriermon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 3,
	"healthPoints": 5,
	"evolution": '664e8b7ceb0218b7c40ce0ce',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ce',
	"price": 4,
	"name": 'Gargomon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 13,
	"healthPoints": 12,
	"evolution": '664e8b7ceb0218b7c40ce0cf',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0cf',
	"price": 7,
	"name": 'Rapidmon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 27,
	"healthPoints": 20,
	"evolution": '664e8b7ceb0218b7c40ce0d0',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d0',
	"price": 10,
	"name": 'MegaGargomon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 50,
	"healthPoints": 50,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d1',
	"price": 1,
	"name": 'Guilmon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 3,
	"healthPoints": 3,
	"evolution": '664e8b7ceb0218b7c40ce0d2',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a2',
	"price": 4,
	"name": 'Greymon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 20,
	"healthPoints": 20,
	"evolution": '664e8b7ceb0218b7c40ce0a3',
	"energyCount": 2,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a3',
	"price": 7,
	"name": 'MetalGreymon (Vaccine)',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 34,
	"healthPoints": 32,
	"evolution": '664e8b7ceb0218b7c40ce0a4',
	"energyCount": 3,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a4',
	"price": 10,
	"name": 'WarGreymon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 60,
	"healthPoints": 55,
	"evolution": null,
	"energyCount": 4,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a5',
	"price": 1,
	"name": 'Gabumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 4,
	"healthPoints": 3,
	"evolution": '664e8b7ceb0218b7c40ce0a6',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a6',
	"price": 4,
	"name": 'Garurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 14,
	"healthPoints": 14,
	"evolution": '664e8b7ceb0218b7c40ce0a7',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a7',
	"price": 7,
	"name": 'WereGarurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 32,
	"healthPoints": 30,
	"evolution": '664e8b7ceb0218b7c40ce0a8',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a8',
	"price": 10,
	"name": 'MetalGarurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 55,
	"healthPoints": 60,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0a9',
	"price": 1,
	"name": 'Veemon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 4,
	"healthPoints": 4,
	"evolution": '664e8b7ceb0218b7c40ce0aa',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0aa',
	"price": 4,
	"name": 'ExVeemon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 17,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0ab',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ab',
	"price": 7,
	"name": 'Paildramon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 35,
	"healthPoints": 30,
	"evolution": '664e8b7ceb0218b7c40ce0ac',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ac',
	"price": 10,
	"name": 'Imperialdramon Fighter Mode',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 65,
	"healthPoints": 50,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ad',
	"price": 1,
	"name": 'Patamon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 1,
	"healthPoints": 4,
	"evolution": '664e8b7ceb0218b7c40ce0ae',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ae',
	"price": 4,
	"name": 'Angemon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 14,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0af',
	"energyCount": 2,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0af',
	"price": 7,
	"name": 'MagnaAngemon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 31,
	"healthPoints": 33,
	"evolution": '664e8b7ceb0218b7c40ce0b0',
	"energyCount": 3,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b0',
	"price": 10,
	"name": 'Seraphimon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 50,
	"healthPoints": 65,
	"evolution": null,
	"energyCount": 4,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b1',
	"price": 1,
	"name": 'Salamon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 0,
	"healthPoints": 5,
	"evolution": '664e8b7ceb0218b7c40ce0b2',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b2',
	"price": 4,
	"name": 'Gatomon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 13,
	"healthPoints": 14,
	"evolution": '664e8b7ceb0218b7c40ce0b3',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b3',
	"price": 7,
	"name": 'Angewomon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 31,
	"healthPoints": 33,
	"evolution": '664e8b7ceb0218b7c40ce0b4',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b4',
	"price": 10,
	"name": 'Ophanimon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 65,
	"healthPoints": 50,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b5',
	"price": 1,
	"name": 'Biyomon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 2,
	"healthPoints": 2,
	"evolution": '664e8b7ceb0218b7c40ce0b6',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b6',
	"price": 4,
	"name": 'Birdramon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 11,
	"healthPoints": 9,
	"evolution": '664e8b7ceb0218b7c40ce0b7',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b7',
	"price": 7,
	"name": 'Garudamon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 30,
	"healthPoints": 25,
	"evolution": '664e8b7ceb0218b7c40ce0b8',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b8',
	"price": 10,
	"name": 'Phoenixmon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 45,
	"healthPoints": 43,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0b9',
	"price": 1,
	"name": 'Tentomon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 2,
	"healthPoints": 3,
	"evolution": '664e8b7ceb0218b7c40ce0ba',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ba',
	"price": 4,
	"name": 'Kabuterimon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 14,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0bb',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0bb',
	"price": 7,
	"name": 'MegaKabuterimon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 33,
	"healthPoints": 36,
	"evolution": '664e8b7ceb0218b7c40ce0bc',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0bc',
	"price": 10,
	"name": 'HerculesKabuterimon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 50,
	"healthPoints": 50,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0bd',
	"price": 1,
	"name": 'Palmon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 2,
	"healthPoints": 2,
	"evolution": '664e8b7ceb0218b7c40ce0be',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0be',
	"price": 4,
	"name": 'Togemon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 12,
	"healthPoints": 12,
	"evolution": '664e8b7ceb0218b7c40ce0bf',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0bf',
	"price": 7,
	"name": 'Lillymon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 27,
	"healthPoints": 25,
	"evolution": '664e8b7ceb0218b7c40ce0c0',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c0',
	"price": 10,
	"name": 'Rosemon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 45,
	"healthPoints": 45,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c1',
	"price": 1,
	"name": 'Gomamon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 2,
	"healthPoints": 3,
	"evolution": '664e8b7ceb0218b7c40ce0c2',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c2',
	"price": 4,
	"name": 'Ikkakumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 13,
	"healthPoints": 13,
	"evolution": '664e8b7ceb0218b7c40ce0c3',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c3',
	"price": 7,
	"name": 'Zudomon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 34,
	"healthPoints": 30,
	"evolution": '664e8b7ceb0218b7c40ce0c4',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c4',
	"price": 10,
	"name": 'Vikemon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 45,
	"healthPoints": 43,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c5',
	"price": 1,
	"name": 'Elecmon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 2,
	"healthPoints": 1,
	"evolution": '664e8b7ceb0218b7c40ce0c6',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c6',
	"price": 4,
	"name": 'Leomon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 16,
	"healthPoints": 18,
	"evolution": '664e8b7ceb0218b7c40ce0c7',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c7',
	"price": 7,
	"name": 'IceLeomon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 21,
	"healthPoints": 17,
	"evolution": '664e8b7ceb0218b7c40ce0c8',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c8',
	"price": 10,
	"name": 'Saberdramon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 40,
	"healthPoints": 40,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0c9',
	"price": 1,
	"name": 'Renamon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 4,
	"healthPoints": 4,
	"evolution": '664e8b7ceb0218b7c40ce0ca',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ca',
	"price": 4,
	"name": 'Kyubimon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 15,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0cb',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0cb',
	"price": 7,
	"name": 'Taomon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 32,
	"healthPoints": 30,
	"evolution": '664e8b7ceb0218b7c40ce0cc',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0cc',
	"price": 10,
	"name": 'Sakuyamon',
	"color": DB.COLORS_CARD.WHITE,
	"attackPoints": 50,
	"healthPoints": 50,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0cd',
	"price": 1,
	"name": 'Terriermon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 3,
	"healthPoints": 5,
	"evolution": '664e8b7ceb0218b7c40ce0ce',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0ce',
	"price": 4,
	"name": 'Gargomon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 13,
	"healthPoints": 12,
	"evolution": '664e8b7ceb0218b7c40ce0cf',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0cf',
	"price": 7,
	"name": 'Rapidmon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 27,
	"healthPoints": 20,
	"evolution": '664e8b7ceb0218b7c40ce0d0',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d0',
	"price": 10,
	"name": 'MegaGargomon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 50,
	"healthPoints": 50,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d1',
	"price": 1,
	"name": 'Guilmon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 3,
	"healthPoints": 3,
	"evolution": '664e8b7ceb0218b7c40ce0d2',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d2',
	"price": 4,
	"name": 'Growlmon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 18,
	"healthPoints": 20,
	"evolution": '664e8b7ceb0218b7c40ce0d3',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d3',
	"price": 7,
	"name": 'WarGrowlmon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 33,
	"healthPoints": 30,
	"evolution": '664e8b7ceb0218b7c40ce0d4',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d4',
	"price": 10,
	"name": 'Gallantmon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 56,
	"healthPoints": 69,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d5',
	"price": 1,
	"name": 'Impmon',
	"color": DB.COLORS_CARD.BLACK,
	"attackPoints": 2,
	"healthPoints": 1,
	"evolution": '664e8b7ceb0218b7c40ce0d6',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d6',
	"price": 4,
	"name": 'Wizardmon',
	"color": DB.COLORS_CARD.BLACK,
	"attackPoints": 13,
	"healthPoints": 11,
	"evolution": '664e8b7ceb0218b7c40ce0d7',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d7',
	"price": 7,
	"name": 'Mistymon',
	"color": DB.COLORS_CARD.BLACK,
	"attackPoints": 21,
	"healthPoints": 17,
	"evolution": '664e8b7ceb0218b7c40ce0d8',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d8',
	"price": 10,
	"name": 'Dynasmon',
	"color": DB.COLORS_CARD.BLACK,
	"attackPoints": 43,
	"healthPoints": 45,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d9',
	"price": 1,
	"name": 'Kumamon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 5,
	"healthPoints": 5,
	"evolution": '664e8b7ceb0218b7c40ce0da',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0da',
	"price": 4,
	"name": 'Grizzlymon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 16,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0db',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0db',
	"price": 7,
	"name": 'Gigasmon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 27,
	"healthPoints": 25,
	"evolution": '664e8b7ceb0218b7c40ce0dc',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0dc',
	"price": 10,
	"name": 'Hisyaryumon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 43,
	"healthPoints": 47,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0dd',
	"price": 1,
	"name": 'Agunimon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 5,
	"healthPoints": 2,
	"evolution": '664e8b7ceb0218b7c40ce0de',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0de',
	"price": 4,
	"name": 'BurningGreymon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 13,
	"healthPoints": 17,
	"evolution": '664e8b7ceb0218b7c40ce0df',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0df',
	"price": 7,
	"name": 'Aldamon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 28,
	"healthPoints": 22,
	"evolution": '664e8b7ceb0218b7c40ce0e0',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e0',
	"price": 10,
	"name": 'EmperorGreymon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 59,
	"healthPoints": 56,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e1',
	"price": 1,
	"name": 'Lobomon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 2,
	"healthPoints": 3,
	"evolution": '664e8b7ceb0218b7c40ce0e2',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e2',
	"price": 4,
	"name": 'KendoGarurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 14,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0e3',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e3',
	"price": 7,
	"name": 'BeoWolfmon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 26,
	"healthPoints": 28,
	"evolution": '664e8b7ceb0218b7c40ce0e4',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e4',
	"price": 10,
	"name": 'Magnagarurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 59,
	"healthPoints": 56,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d3',
	"price": 7,
	"name": 'WarGrowlmon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 33,
	"healthPoints": 30,
	"evolution": '664e8b7ceb0218b7c40ce0d4',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d4',
	"price": 10,
	"name": 'Gallantmon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 56,
	"healthPoints": 69,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d5',
	"price": 1,
	"name": 'Impmon',
	"color": DB.COLORS_CARD.BLACK,
	"attackPoints": 2,
	"healthPoints": 1,
	"evolution": '664e8b7ceb0218b7c40ce0d6',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d6',
	"price": 4,
	"name": 'Wizardmon',
	"color": DB.COLORS_CARD.BLACK,
	"attackPoints": 13,
	"healthPoints": 11,
	"evolution": '664e8b7ceb0218b7c40ce0d7',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d7',
	"price": 7,
	"name": 'Mistymon',
	"color": DB.COLORS_CARD.BLACK,
	"attackPoints": 21,
	"healthPoints": 17,
	"evolution": '664e8b7ceb0218b7c40ce0d8',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d8',
	"price": 10,
	"name": 'Dynasmon',
	"color": DB.COLORS_CARD.BLACK,
	"attackPoints": 43,
	"healthPoints": 45,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0d9',
	"price": 1,
	"name": 'Kumamon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 5,
	"healthPoints": 5,
	"evolution": '664e8b7ceb0218b7c40ce0da',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0da',
	"price": 4,
	"name": 'Grizzlymon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 16,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0db',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0db',
	"price": 7,
	"name": 'Gigasmon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 27,
	"healthPoints": 25,
	"evolution": '664e8b7ceb0218b7c40ce0dc',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0dc',
	"price": 10,
	"name": 'Hisyaryumon',
	"color": DB.COLORS_CARD.GREEN,
	"attackPoints": 43,
	"healthPoints": 47,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0dd',
	"price": 1,
	"name": 'Agunimon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 5,
	"healthPoints": 2,
	"evolution": '664e8b7ceb0218b7c40ce0de',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0de',
	"price": 4,
	"name": 'BurningGreymon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 13,
	"healthPoints": 17,
	"evolution": '664e8b7ceb0218b7c40ce0df',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0df',
	"price": 7,
	"name": 'Aldamon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 28,
	"healthPoints": 22,
	"evolution": '664e8b7ceb0218b7c40ce0e0',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e0',
	"price": 10,
	"name": 'EmperorGreymon',
	"color": DB.COLORS_CARD.RED,
	"attackPoints": 59,
	"healthPoints": 56,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e1',
	"price": 1,
	"name": 'Lobomon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 2,
	"healthPoints": 3,
	"evolution": '664e8b7ceb0218b7c40ce0e2',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 1,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e2',
	"price": 4,
	"name": 'KendoGarurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 14,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0e3',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e3',
	"price": 7,
	"name": 'BeoWolfmon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 26,
	"healthPoints": 28,
	"evolution": '664e8b7ceb0218b7c40ce0e4',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e4',
	"price": 10,
	"name": 'Magnagarurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 59,
	"healthPoints": 56,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e2',
	"price": 4,
	"name": 'KendoGarurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 14,
	"healthPoints": 16,
	"evolution": '664e8b7ceb0218b7c40ce0e3',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 2,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e3',
	"price": 7,
	"name": 'BeoWolfmon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 26,
	"healthPoints": 28,
	"evolution": '664e8b7ceb0218b7c40ce0e4',
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 3,
  }),
  CardDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0e4',
	"price": 10,
	"name": 'Magnagarurumon',
	"color": DB.COLORS_CARD.BLUE,
	"attackPoints": 59,
	"healthPoints": 56,
	"evolution": null,
	"energyCount": 1,
	"type": DB.CARD_TYPE.DIGIMON,
	"level": 4,
  }),
  CardEquipment.new({
	"_id": '664e8b7ceb0218b7c40ce0e5',
	"price": 2,
	"name": 'Armor +10',
	"attackPoints": 0,
	"healthPoints": 10,
	"targetScope": 'UNIQUE',
	"type": DB.CARD_TYPE.EQUIPMENT,
	"quantityOfTargets": 1,
  }),
  CardEquipment.new({
	"_id": '664e8b7ceb0218b7c40ce0e6',
	"price": 2,
	"name": 'Sword +10',
	"attackPoints": 10,
	"healthPoints": 0,
	"targetScope": 'UNIQUE',
	"type": DB.CARD_TYPE.EQUIPMENT,
	"quantityOfTargets": 1,
  }),
  CardEquipment.new({
	"_id": '664e8b7ceb0218b7c40ce0e7',
	"price": 1,
	"name": 'Armor 2x +10',
	"attackPoints": 0,
	"healthPoints": 10,
	"targetScope": 'PARTIAL',
	"type": DB.CARD_TYPE.EQUIPMENT,
	"quantityOfTargets": 2,
  }),
  CardEquipment.new({
	"_id": '664e8b7ceb0218b7c40ce0e8',
	"price": 1,
	"name": 'Armor 3x +10',
	"attackPoints": 0,
	"healthPoints": 10,
	"targetScope": 'PARTIAL',
	"type": DB.CARD_TYPE.EQUIPMENT,
	"quantityOfTargets": 3,
  }),
  CardEquipment.new({
	"_id": '664e8b7ceb0218b7c40ce0e9',
	"price": 1,
	"name": 'Armor 4x +10',
	"attackPoints": 0,
	"healthPoints": 10,
	"targetScope": 'PARTIAL',
	"type": DB.CARD_TYPE.EQUIPMENT,
	"quantityOfTargets": 4,
  }),
  CardEquipment.new({
	"_id": '664e8b7ceb0218b7c40ce0ea',
	"price": 1,
	"name": 'Sword 2x +10',
	"attackPoints": 10,
	"healthPoints": 0,
	"targetScope": 'PARTIAL',
	"type": DB.CARD_TYPE.EQUIPMENT,
	"quantityOfTargets": 2,
  }),
  CardEquipment.new({
	"_id": '664e8b7ceb0218b7c40ce0eb',
	"price": 1,
	"name": 'Sword 3x +10',
	"attackPoints": 10,
	"healthPoints": 0,
	"targetScope": 'PARTIAL',
	"type": DB.CARD_TYPE.EQUIPMENT,
	"quantityOfTargets": 3,
  }),
  CardEquipment.new({
	"_id": '664e8b7ceb0218b7c40ce0ec',
	"price": 1,
	"name": 'Sword 4x +10',
	"attackPoints": 10,
	"healthPoints": 0,
	"targetScope": 'PARTIAL',
	"type": DB.CARD_TYPE.EQUIPMENT,
	"quantityOfTargets": 4,
  }),
  CardEquipment.new({
	"_id": '664e8b7ceb0218b7c40ce0ed',
	"price": 1,
	"name": 'Aura',
	"attackPoints": 10,
	"healthPoints": 10,
	"targetScope": 'ALL',
	"type": DB.CARD_TYPE.EQUIPMENT,
	"quantityOfTargets": null,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0ee',
	"price": 1,
	"name": 'Red Energy +1',
	"color": DB.COLORS_CARD.RED,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0ef',
	"price": 1,
	"name": 'Green Energy +1',
	"color": DB.COLORS_CARD.GREEN,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f0',
	"price": 1,
	"name": 'Black Energy +1',
	"color": DB.COLORS_CARD.BLACK,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f1',
	"price": 1,
	"name": 'Blue Energy +1',
	"color": DB.COLORS_CARD.BLUE,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f2',
	"price": 1,
	"name": 'White Energy +1',
	"color": DB.COLORS_CARD.WHITE,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f3',
	"price": 1,
	"name": 'Brown Energy +1',
	"color": DB.COLORS_CARD.BROWN,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0ee',
	"price": 1,
	"name": 'Red Energy +1',
	"color": DB.COLORS_CARD.RED,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0ef',
	"price": 1,
	"name": 'Green Energy +1',
	"color": DB.COLORS_CARD.GREEN,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f0',
	"price": 1,
	"name": 'Black Energy +1',
	"color": DB.COLORS_CARD. BLACK,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f1',
	"price": 1,
	"name": 'Blue Energy +1',
	"color": DB.COLORS_CARD.BLUE,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f2',
	"price": 1,
	"name": 'White Energy +1',
	"color": DB.COLORS_CARD.WHITE,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f3',
	"price": 1,
	"name": 'Brown Energy +1',
	"color":DB.COLORS_CARD. BROWN,
	"energyCount": 1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f4',
	"price": 1,
	"name": 'Red Energy -1',
	"color": DB.COLORS_CARD.RED,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f5',
	"price": 1,
	"name": 'Green Energy -1',
	"color": DB.COLORS_CARD.GREEN,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f6',
	"price": 1,
	"name": 'Black Energy -1',
	"color":DB.COLORS_CARD. BLACK,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f7',
	"price": 1,
	"name": 'Blue Energy -1',
	"color":DB.COLORS_CARD. BLUE,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f8',
	"price": 1,
	"name": 'White Energy -1',
	"color":DB.COLORS_CARD. WHITE,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f9',
	"price": 1,
	"name": 'Brown Energy -1',
	"color": DB.COLORS_CARD.BROWN,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f5',
	"price": 1,
	"name": 'Green Energy -1',
	"color":DB.COLORS_CARD.GREEN,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f6',
	"price": 1,
	"name": 'Black Energy -1',
	"color": DB.COLORS_CARD.BLACK,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f7',
	"price": 1,
	"name": 'Blue Energy -1',
	"color": DB.COLORS_CARD.BLUE,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f8',
	"price": 1,
	"name": 'White Energy -1',
	"color": DB.COLORS_CARD.WHITE,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f9',
	"price": 1,
	"name": 'Brown Energy -1',
	"color": DB.COLORS_CARD.BROWN,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f6',
	"price": 1,
	"name": 'Black Energy -1',
	"color": DB.COLORS_CARD.BLACK,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f7',
	"price": 1,
	"name": 'Blue Energy -1',
	"color": DB.COLORS_CARD.BLUE,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f8',
	"price": 1,
	"name": 'White Energy -1',
	"color":DB.COLORS_CARD. WHITE,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f9',
	"price": 1,
	"name": 'Brown Energy -1',
	"color": DB.COLORS_CARD.BROWN,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f7',
	"price": 1,
	"name": 'Blue Energy -1',
	"color": DB.COLORS_CARD.BLUE,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f8',
	"price": 1,
	"name": 'White Energy -1',
	"color": DB.COLORS_CARD.WHITE,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardEnergy.new({
	"_id": '664e8b7ceb0218b7c40ce0f9',
	"price": 1,
	"name": 'Brown Energy -1',
	"color": DB.COLORS_CARD.BROWN,
	"energyCount": -1,
	"type": DB.CARD_TYPE.ENERGY,
  }),
  CardSummonDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0fa',
	"price": 1,
	"name": 'Summon Gatomon x2',
	"digimonsCards": [
	  {
		"cardDigimonId": '664e8b7ceb0218b7c40ce0fb',
		"price": 1,
		"name": 'Gatomon',
		"color": DB.COLORS_CARD.WHITE,
		"attack": 10,
		"defense": 10,
		"evolution": { "price": 1, "name": 'Angewomon', "color": DB.COLORS_CARD.WHITE },
		"type": DB.CARD_TYPE.DIGIMON,
		"level": 2,
	  } ,
	  {
		"cardDigimonId": '664e8b7ceb0218b7c40ce0fc',
		"price": 1,
		"name": 'Gatomon',
		"color": DB.COLORS_CARD.WHITE,
		"attack": 10,
		"defense": 10,
		"evolution": { "price": 1, "name": 'Angewomon', "color":DB.COLORS_CARD. WHITE },
		"type": DB.CARD_TYPE.DIGIMON,
		"level": 2,
	  } 
	],
	"type": DB.CARD_TYPE.SUMMON_DIGIMON,
  }),
  CardSummonDigimon.new({
	"_id": '664e8b7ceb0218b7c40ce0fd',
	"price": 1,
	"name": 'Summon Angemon x2',
	"digimonsCards": [
	 {
		"cardDigimonId": '664e8b7ceb0218b7c40ce0fe',
		"price": 1,
		"name": 'Angemon',
		"color": DB.COLORS_CARD.WHITE,
		"attack": 10,
		"defense": 10,
		"evolution": { "price": 1, "name": 'MagnaAngemon', "color": DB.COLORS_CARD.WHITE },
		"type": DB.CARD_TYPE.DIGIMON,
		"level": 2,
	  },
	 {
		"cardDigimonId": '664e8b7ceb0218b7c40ce0ff',
		"price": 1,
		"name": 'Angemon',
		"color":DB.COLORS_CARD. WHITE,
		"attack": 10,
		"defense": 10,
		"evolution": { "price": 1, "name": 'MagnaAngemon', "color": DB.COLORS_CARD.WHITE },
		"type": DB.CARD_TYPE.DIGIMON,
		"level": 2,
	  }
	],
	"type": DB.CARD_TYPE.SUMMON_DIGIMON,
  }),
];

var isSelected = false
var isHovered = false
var interactive: bool = true
# Called when the node enters the scene tree for the first time.
var CardInformation: CardDigimon = CARDS_DATA[0];  # fallback por compatibilidad; usar set_card_data() para mostrar otra carta

signal flip_animation_finished
signal card_selected(card_data: Card, is_selected: bool)
signal card_hovered(card_data: Card)
signal card_unhovered

func set_card_data(card_data: CardDigimon) -> void:
	CardInformation = card_data

func set_interactive(value: bool) -> void:
	interactive = value

func _ready():
	var is_digimon_card = CardInformation is CardDigimon
	var nameCard = CardInformation.name

	var baseWidth = $Panel/CardImage.texture.get_size().x * $Panel/CardImage.scale.x
	var baseHeight = $Panel/CardImage.texture.get_size().y * $Panel/CardImage.scale.y

	if is_digimon_card:
		var CardImg = str("res://digimon-images/", CardInformation.name, ".jpg")
		$Panel/CardImage.texture = load(CardImg)
	else:
		# Cartas de Programación/Equipment/Energy/SummonDigimon no tienen arte propio: ícono genérico placeholder
		$Panel/CardImage.texture = load("res://card_back4.webp")

	var imgWidth = $Panel/CardImage.texture.get_size().x
	var imgHeight = $Panel/CardImage.texture.get_size().y

	var scale_factor_width = baseWidth / imgWidth
	var scale_factor_height = baseHeight / imgHeight

	$Panel/CardImage.scale = Vector2(scale_factor_width, scale_factor_height)

	$Panel/Name.text = str(nameCard)

	if is_digimon_card:
		var attack = str(CardInformation.attackPoints)
		var deffense = str(CardInformation.healthPoints)
		var labelAtkHp = "{atk}/{hp}"
		$Panel/Atk.text = labelAtkHp.format({"atk": attack, "hp": deffense})
		$Panel/Atk.visible = true
	else:
		$Panel/Atk.text = ""
		$Panel/Atk.visible = false

	var color = null
	if CardInformation is CardDigimon: # || CardInformation is CardEnergy:
		color = CardInformation.color

	var styleBoxFlat: StyleBoxFlat = $Panel.get_theme_stylebox("panel").duplicate()
	var styleBoxFlatName: StyleBoxFlat = $Panel/Name.get_theme_stylebox("normal").duplicate()
	var styleBoxFlatAtk: StyleBoxFlat = $Panel/Atk.get_theme_stylebox("normal").duplicate()
	if styleBoxFlat is StyleBoxFlat and color != null:
		if color == DB.COLORS_CARD.get("RED"):
			styleBoxFlat.border_color = Color.RED
		if color == DB.COLORS_CARD.get("BLUE"):
			styleBoxFlat.border_color = Color(100, 2, 0)  # Rojo

	if styleBoxFlatName is StyleBoxFlat and color != null:
		if color == DB.COLORS_CARD.get("RED"):
			styleBoxFlatName.border_color = Color.RED
		if color == DB.COLORS_CARD.get("BLUE"):
			styleBoxFlatName.border_color = Color(100, 2, 0)  # Rojo

	if styleBoxFlatAtk is StyleBoxFlat and color != null:
		if color == DB.COLORS_CARD.get("RED"):
			styleBoxFlatAtk.bg_color = Color.DARK_RED

	$Panel/Name.add_theme_stylebox_override("normal", styleBoxFlatName)

	$Panel/Atk.add_theme_stylebox_override("normal", styleBoxFlatAtk)

	$Panel.add_theme_stylebox_override("panel", styleBoxFlat)

	$Area2D.mouse_entered.connect(_on_area_2d_mouse_entered)
	$Area2D.mouse_exited.connect(_on_area_2d_mouse_exited)
	$Area2D.input_event.connect(_on_area_2d_input_event)
	$AnimationPlayer.animation_finished.connect(_on_animation_finished)
	$AnimationPlayer.play("card_flip")

func update_stats_display(new_ap: int, new_hp: int) -> void:
	if CardInformation is CardDigimon:
		CardInformation.attackPoints = new_ap
		CardInformation.healthPoints = new_hp
	var labelAtkHp = "{atk}/{hp}"
	$Panel/Atk.text = labelAtkHp.format({"atk": str(new_ap), "hp": str(new_hp)})

func _on_animation_finished(anim_name: StringName) -> void:
	if anim_name == "card_flip":
		flip_animation_finished.emit()

func _draw():
	pass



# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass


func _on_area_2d_mouse_entered() -> void:
	if not interactive:
		return
	highlight_card(true)
	card_hovered.emit(CardInformation)

func _on_area_2d_mouse_exited() -> void:
	if not interactive:
		return
	highlight_card(false)
	card_unhovered.emit()

func highlight_card(_isHovered):
	if(_isHovered):
		self.scale = Vector2(1.05, 1.05)
	else:
		self.scale = Vector2(1, 1)


func alternateColorWhenClick() -> void:
	var styleBoxFlat: StyleBoxFlat = $Panel.get_theme_stylebox("panel").duplicate()

	if styleBoxFlat.border_color == Color.GOLD:
		if CardInformation is CardDigimon and CardInformation.color == DB.COLORS_CARD.RED:
			styleBoxFlat.border_color = Color.RED
	else:
		styleBoxFlat.border_color = Color.GOLD

	$Panel.add_theme_stylebox_override("panel", styleBoxFlat)

func moveUp():
	self.position.y = self.position.y - 50

func moveDown():
	self.position.y = self.position.y + 50

func _on_area_2d_input_event(_viewport, event, _shape_idx):
	if not interactive:
		return
	if event is InputEventMouseButton and event.pressed:
		if !isSelected:
			alternateColorWhenClick()
			moveUp()
			isSelected = true
		else:
			alternateColorWhenClick()
			moveDown()
			isSelected = false
		card_selected.emit(CardInformation, isSelected)
			
